# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute prior distribution of Multiscale Mixture of Kernels
#'
#' @param TH: Binary tree of location parameters
#' @param SIG: Binary tree of scale matrices
#' @param prob: Binary tree of node probabilities
#' @param Ssh: Binary tree of conditional stopping probabilities
#' @param Rsh: Binary tree of conditional right-turn probabilities
#' @param thrs: Binary tree of matrices with thresholds for each dimension
#' @param mu0: Prior mean vector of G_0.
#' @param k0: Prior marginal variances of G_0.
#' @param sig0: Prior covariance matrix of H_0.
#' @param a: Prior stick-breaking weight.
#' @param b: Prior stick-breaking weight.
#' @param delta: Prior stick-breaking weight.
#' @param indep: If TRUE assumes diagonal scale matrix.
#' @param verbose: If TRUE prints information about the constructed variables
#'
#' @return List of values pertaining to the prior multiscale distribution
NULL

rinvgamma <- function(shape, scale) {
    .Call(`_msMK_rinvgamma`, shape, scale)
}

#' Compute msMK density on a set of points
#'
#' @param x: Matrix of size n x p, containing n points onto which to evaluate the density
#' @param TH: Field of vectors, sequence of location parameters for the density 
#' @param SIG: Field of matrices, sequence of scale parameters for the density
#' @param prob: vector of doubles, contains probabilities of each cluster
#'
#' @return two-column matrix where every row (s_i, h_i) is the cluster allocation of the i-th data point
dmsMK <- function(x, TH, SIG, thrs, prob, indep) {
    .Call(`_msMK_dmsMK`, x, TH, SIG, thrs, prob, indep)
}

msMK_mcmc_test <- function(sample, y, a, b, delta, smax, mu0, k0, sig0, indep, lbNumpy, ubNumpy, burnin) {
    .Call(`_msMK_msMK_mcmc_test`, sample, y, a, b, delta, smax, mu0, k0, sig0, indep, lbNumpy, ubNumpy, burnin)
}

